FRAMECHANNEL=1
ifdef FRAMECHANNEL
	CFLAGS += -DFRAMECHANNEL=$(FRAMECHANNEL)
endif

#UPNP_CONTROLLER=1
ifdef UPNP_CONTROLLER
	CFLAGS += -DUPNP_CONTROLLER=$(UPNP_CONTROLLER)
endif

ALWAYS_CHECK_DOMAIN_NAME=1
ifdef ALWAYS_CHECK_DOMAIN_NAME
	CFLAGS += -DALWAYS_CHECK_DOMAIN_NAME=$(ALWAYS_CHECK_DOMAIN_NAME)
endif
