# $Id: Makefile,v 1.1.1.1 2006/04/03 08:40:36 amos_lee Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
