/* the first pair may be overwritten by generic.c init code so we place these here */
#define DEFAULT_GENERIC_VENDOR_ID			0x05f9
#define DEFAULT_GENERIC_PRODUCT_ID 			0xffff

/* Vendor and product IDs */
#define OPTION_VENDOR_ID 					0x0AF0
#define HUAWEI_VENDOR_ID 					0x12D1
#define BANDRICH_VENDOR_ID 					0x1A8D
#define AUDIOVOX_VENDOR_ID 					0x0F3D

#define OPTION_PRODUCT_OLD 					0x5000
#define OPTION_PRODUCT_FUSION 				0x6000
#define OPTION_PRODUCT_FUSION2 				0x6300
#define HUAWEI_PRODUCT_E600 				0x1001
#define BANDRICH_PRODUCT_C100S 				0x1002
#define BANDRICH_PRODUCT_C100 				0x1003
#define AUDIOVOX_PRODUCT_AIRCARD 			0x0112

//joel patch from google
#define TELEWELL_VENDOR_ID 					0x1C15
#define TELEWELL_PRODUCT_TW_3G_PLUS 		0x1002

#define RCG_VENDOR_ID 						0x1761
#define RCG_PRODUCT_FXSECURE_KEY 			0x1002

#define DLINK_VENDOR_ID 					0x1186
#define DLINK_PRODUCT_DWM_652 				0x3E04

#define BANDRICH_PRODUCT_C100_1 			0x1002
#define BANDRICH_PRODUCT_C100_2 			0x1003

static struct usb_device_id alpha_device_id_list[] = {
	{ DEFAULT_GENERIC_VENDOR_ID, DEFAULT_GENERIC_PRODUCT_ID },
	{ USB_DEVICE(OPTION_VENDOR_ID, OPTION_PRODUCT_OLD) },
	{ USB_DEVICE(OPTION_VENDOR_ID, OPTION_PRODUCT_FUSION) },
	{ USB_DEVICE(OPTION_VENDOR_ID, OPTION_PRODUCT_FUSION2) },
	{ USB_DEVICE(HUAWEI_VENDOR_ID, HUAWEI_PRODUCT_E600) },
	{ USB_DEVICE(BANDRICH_VENDOR_ID, BANDRICH_PRODUCT_C100S) },
	{ USB_DEVICE(BANDRICH_VENDOR_ID, BANDRICH_PRODUCT_C100) },
	{ USB_DEVICE(AUDIOVOX_VENDOR_ID, AUDIOVOX_PRODUCT_AIRCARD) },
	{ USB_DEVICE(TELEWELL_VENDOR_ID, TELEWELL_PRODUCT_TW_3G_PLUS) },
    { USB_DEVICE(RCG_VENDOR_ID, RCG_PRODUCT_FXSECURE_KEY) },
    { USB_DEVICE(DLINK_VENDOR_ID, DLINK_PRODUCT_DWM_652) },
	{}
};
