#!/bin/sh
# Cable test for LAN 1. See 'switch' for port mapping.
#. /etc/config/defines
usage="Usage cabletest:2 [-g|-s] [xml node] {value}"
vctfile="/var/run/port2.vct"
case "$1" in
"-g")
	case "$2" in
	"txstatus")
		[ -f "$vctfile" ] && scut -p 'TXSTATUS=' $vctfile
		;;
	"txmeter")
		[ -f "$vctfile" ] && scut -p 'TXMETER=' $vctfile
		;;
	"rxstatus")
		[ -f "$vctfile" ] && scut -p 'RXSTATUS=' $vctfile
		;;
	"rxmeter")
		[ -f "$vctfile" ] && scut -p 'RXMETER=' $vctfile
		;;
	esac
	;;
"-s")
	[ -f "$vctfile" ] && rm -f "$vctfile"
	ctest -i 0 > $vctfile
	rgdb -i -s /runtime/cabletest:2/txstatus	`scut -p 'STATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:2/txmeter		`scut -p 'METER=' $vctfile`
	rgdb -i -s /runtime/cabletest:2/rxstatus	`scut -p 'STATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:2/rxmeter		`scut -p 'METER=' $vctfile`
	;;
*)
	echo $usage
	;;
esac
