#!/bin/sh
# Cable test for LAN 4. See 'switch' for port mapping
#. /etc/config/defines
usage="Usage cabletest:5 [-g|-s] [xml node] {value}"
vctfile="/var/run/port5.vct"
case "$1" in
"-g")
	case "$2" in
	"txstatus")
		[ -f "$vctfile" ] && scut -p 'TXSTATUS=' $vctfile
		;;
	"txmeter")
		[ -f "$vctfile" ] && scut -p 'TXMETER=' $vctfile
		;;
	"rxstatus")
		[ -f "$vctfile" ] && scut -p 'RXSTATUS=' $vctfile
		;;
	"rxmeter")
		[ -f "$vctfile" ] && scut -p 'RXMETER=' $vctfile
		;;
	esac
	;;
"-s")
	[ -f "$vctfile" ] && rm -f "$vctfile"
	ctest -i 3 > $vctfile
	rgdb -i -s /runtime/cabletest:5/txstatus	`scut -p 'STATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:5/txmeter		`scut -p 'METER=' $vctfile`
	rgdb -i -s /runtime/cabletest:5/rxstatus	`scut -p 'STATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:5/rxmeter		`scut -p 'METER=' $vctfile`
	;;
*)
	echo $usage
	;;
esac
