#ifndef _FCRSS_COMMAND_H_
#define _FCRSS_COMMAND_H_

#define CHANNEL_LIST_GET 110
#define CHANNEL_LIST_UPDATE 111
#define CHANNEL_LIST_DELETE 112
#define CHANNEL_GET 113
#define CHANNEL_UPDATE 114
#define CHANNEL_DELETE 115
#define SEND_GUID 116
#define PRINT_TREE 117
#define CHANNEL_PIC_GET 118
#define FCNODE_ISNULL 119
#define FCNODE_NOTNULL 120
#define CHANNEL_SHOW_GET 121
#define RESET_FRAMEID 122
#define RESET_FRAMEID_FAIL 123
#define UNIXSOCK_FAIL 124
#define UPDATE_SUCCESS 125
#define DNS_ERROR 126
#define DO_UPDATE 127
#define DO_NOTHING 128
#define CHECK_FRAMECHANNEL_STATUS 129
#define GET_CHANNELS_UPDATE_VERSION 130	
#define GET_CHANNEL_SHOW_UPDATE_VERSION 131 	
#define WAN_ERROR 132
#define FC_ERROR 133
#define EVER_REGISTER 134
#define NEVER_REGISTER 135
#define GET_ACTIVE_CODE 136
#define CHANNEL_SHOW_UPDATE 137
#define GET_ACTIVE_CODE_FAIL 138
#define GET_ACTIVE_CODE_FINISH 139
#define CHECK_REGISTER_STATUS 140
#define CHECK_SERVER_STATUS 141
#define REQ_SUCCESS 142
#define REQ_FAIL 143
#define UPDATE_FAIL 144
#define CHANNEL_THREAD_STOP 145
#define CHANNEL_SHOW_THREAD_STOP 146
#define CHANNEL_LIST_THREAD_STOP 147

#endif
 

 
