#!/bin/sh
nvram=`cat /etc/config/nvram`
case "$1" in
init)
	LANMAC=`echo -e $2 | tr [A-Z] [a-z]`
	WANMAC=`echo -e $3 | tr [A-Z] [a-z]`
	HWREV=`echo -e $4 | tr [a-z] [A-Z]`
	CCODE="$5"
	PIN="$6"
	if [ "$LANMAC" != "" ]; then
		RGCMD="$RGCMD -e lanmac=$LANMAC -e wlanmac=$LANMAC"
	fi
	if [ "$WANMAC" != "" ]; then
		RGCMD="$RGCMD -e wanmac=$WANMAC"
	fi
	if [ "$PIN" != "" ]; then
		RGCMD="$RGCMD -e pin=$PIN"
	fi
	[ "$HWREV" = "" ] && HWREV="A1"
	[ "$CCODE" = "" ] && CCODE=840
	echo "rgcfg setenv -n $nvram -e countrycode=$CCODE -e hwrev=$HWREV $RGCMD" > /dev/console
	rgcfg setenv -n $nvram -e countrycode=$CCODE -e hwrev=$HWREV $RGCMD -f
	# Save wireless MAC address to EEPROM
	M1=`echo $LANMAC | cut -d: -f1`
	M2=`echo $LANMAC | cut -d: -f2`
	M3=`echo $LANMAC | cut -d: -f3`
	M4=`echo $LANMAC | cut -d: -f4`
	M5=`echo $LANMAC | cut -d: -f5`
	M6=`echo $LANMAC | cut -d: -f6`
	iwpriv ra0 e2p 04=$M2$M1
	iwpriv ra0 e2p 06=$M4$M3
	iwpriv ra0 e2p 08=$M6$M5
	;;
evm)
	if [ $# -ne 9 ]; then
		echo "usage:"
		echo "  mfc evm ATETXMODE ATETXMCS ATECHANNEL ATETXLEN ATETXBW ATETXFREQOFFSET ATETXPOW0 ATETXPOW1"
		exit 1
	fi
	iwpriv ra0 set ATE=APSTOP
	iwpriv ra0 set ATETXMODE=$2
	iwpriv ra0 set ATETXMCS=$3
	iwpriv ra0 set ATECHANNEL=$4
	iwpriv ra0 set ATETXLEN=$5
	iwpriv ra0 set ATETXBW=$6
	iwpriv ra0 set ATETXCNT=1000000000000
	iwpriv ra0 set ATETXFREQOFFSET=$7
	iwpriv ra0 set ATETXPOW0=$8
	iwpriv ra0 set ATETXPOW1=$9	
	iwpriv ra0 set ATE=TXFRAME
	;;
sen)
	if [ $# -ne 4 ]; then
		echo "usage:"
		echo "mfc sen ATECHANNEL ATERXANT ATETXBW"
		exit 1
	fi
	iwpriv ra0 set ATE=APSTOP
	iwpriv ra0 set ATECHANNEL=$2
	iwpriv ra0 set ATERXANT=$3
	iwpriv ra0 set ATETXBW=0
	iwpriv ra0 set ResetCounter=0
	iwpriv ra0 set ATE=RXFRAME
	iwpriv ra0 stat
	;;
wlan)
	rgdb -s /wireless/enable 1
	rgdb -s /wireless/ssid "$2"
	rgdb -s /wireless/channel "$3"
	rgdb -s /wireless/authtype 0
	rgdb -s /wireless/encrypttype 0
	rgdb -s /wireless/wlanmode 4
	rgdb -s /wireless/bandwidth 2
	rgdb -s /wireless/shortguardinterval 1
	rgdb -s /wireless/mcs/auto 0
	rgdb -s /wireless/mcs/index 15
	/etc/templates/wlan.sh restart
	;;
gethwrev)
	rgcfg getenv -n $nvram -e hwrev
	;;
getwanmac)
	rgcfg getenv -n $nvram -e wanmac
	;;
getlanmac)
	rgcfg getenv -n $nvram -e lanmac
	;;
getpin)
	rgcfg getenv -n $nvram -e pin
	;;
getcountrycode)
	rgcfg getenv -n $nvram -e countrycode
	;;
getwlan)
	SSID=`rgdb -g /wireless/ssid`
	CHANNEL=`rgdb -g /wireless/channel`
	echo SSID=$SSID
	echo Channel=$CHANNEL
	;;
ver)
	/etc/scripts/misc/ver.sh
	;;
freset)
	case "$2" in
	enable)
		fresetd &
		;;
	disable)
		killall fresetd
		;;
	"")
		/etc/scripts/misc/profile.sh reset
		/etc/scripts/misc/profile.sh put
		;;
	esac
	;;
button)
	case "$2" in
	reset)
		cat /proc/nas_gpio/gpio/data_pa_8
		;;
	umount)
		cat /proc/nas_gpio/gpio/data_pa_13
		;;
	esac
	;;
led)
	case "$2" in
	HD_BLUE)
		echo 0 > /proc/nas_gpio/gpio/data_pa_12
		sleep 1
		echo 1 > /proc/nas_gpio/gpio/data_pa_11
		;;
	HD_ORANGE)
		echo 0 > /proc/nas_gpio/gpio/data_pa_11
		sleep 1
		echo 1 > /proc/nas_gpio/gpio/data_pa_12
		;;
	WPS)
		echo 0 > /proc/nas_gpio/gpio/data_pa_7
		;;
	off)
		echo 1 > /proc/nas_gpio/gpio/data_pa_12
		sleep 1
		echo 1 > /proc/nas_gpio/gpio/data_pa_11
		sleep 1
		echo 1 > /proc/nas_gpio/gpio/data_pa_7
		;;
	esac
	;;
pci)
	cat /proc/bus/pci/devices | grep "RT2880 iNIC"
	;;
usb)
	cat /proc/bus/usb/devices | grep "Driver=usb-storage"
	cat /proc/bus/usb/devices | grep "Driver=sxuptp_generic"
	cat /proc/bus/usb/devices | grep "Driver=USB General Driver"
	;;
bridge)
	case "$2" in
	on)
		brctl addif br0 eth1
		;;
	off)
		brctl delif br0 eth1
		;;
	esac
	;;
hd)
	 cat /proc/sata_stat | grep "sd"
	;;
touchpad)
	 cat /proc/touchpad
	;;

*)
	echo "Usage: mfc {command} <params>"
	echo "Commands:"
	echo "  init <lanmac> <wanmac> <hwrev> <countrycode> <pin>"
	echo "                           Init flash"
	echo "  save                     Save current setting to flash"
	echo ""
	echo "  wlan <ssid> <channel>    Switch ssid and channel"
	echo ""
	echo "  gethwrev                 Get H/W revision"
	echo "  getwanmac                Get current WAN mac address"
	echo "  getlanmac                Get current LAN mac address"
	echo "  getcountrycode           Get current country code"
	echo "  getpin                   Get PIN number"
	echo "  ver                      Show firmware version"
	echo ""
	echo "  freset                   Factory reset"
	echo "  freset {enable|disable}  Enable/disable factory reset button."
	echo "                           Note: You need to disable freset before button/led test."
	echo ""
	echo "  button {reset|wps}"
	echo "      reset                Get factory reset button status."
	echo "      wps                  Get WPS button status."
	echo ""
	echo "  led {off|HD_BLUE|HD_ORANGE}"
	echo "      off                  Turn off all the leds under test."
	echo "      HD_BLUE              Turn on hd blue led."
	echo "      HD_ORANGE            Turn on hd orange led."
	echo "      WPS                  Turn on WPS led."
	echo ""
	echo "  usb                      Get USB status."
	echo "  hd                       Get Hard Drive status."
	echo ""
	echo "  evm <ATETXMODE> <ATETXMCS> <ATECHANNEL> <ATETXLEN> <ATETXBW> <ATETXFREQOFFSET> <ATETXPOW0> <ATETXPOW1>"
	echo "                           burn the ATE wireless parameters in to the EEPROM"
	echo ""
	echo "  sen <ATECHANNEL> <ATERXANT> <ATETXBW>"
	;;
esac
