#!/bin/sh
echo [$0] $1 ... > /dev/console
TROOT="/etc/templates"
SCRIPT="/etc/scripts"
SYNCWITH=`xmldbc -g /time/syncwith`
case "$1" in
WOL)
	$TROOT/wol.sh start> /dev/console
	;;
LCD_SET_TIMEOUT)
	ssignal 35 &
	;;
HD_RESTART_SLEEPTIME)
	$TROOT/hd_sleeptime.sh stop > /dev/console
	$TROOT/hd_sleeptime.sh start > /dev/console
	;;
BT_START)
	$TROOT/bt.sh start> /dev/console &	
		;;
BT_STOP)
	$TROOT/bt.sh stop> /dev/console &
		;;
QUOTA)
        /sbin/quotaon -avug
        ;;
QUOTA_STOP)
        /sbin/quotaoff -a
        ;;
UPNP_AV_REFRESH)
	$TROOT/prescan.sh now> /dev/console &
		;;
UPNP_AV_STOP)
	$TROOT/upnp_av.sh stop> /dev/console &
	;;
UPNP_AV_START)
	$TROOT/upnp_av.sh restart> /dev/console &
	;;
GROUP_ADD)
	$TROOT/group.sh add > /dev/console &
	;;
USER_ADD)
	$TROOT/user.sh add > /dev/console &
	;;
NET_ACCESS)
	$TROOT/network_access.sh restart > /dev/console &
	;;
NET_ACCESS_RELOAD)
	$TROOT/network_access.sh reload > /dev/console &
	;;
NET_ACCESS_STOP)
	$TROOT/network_access.sh stop > /dev/console &
	;;
ITUNES_STOP)
	$TROOT/itunes_server.sh stop > /dev/console &
	;;
ITUNES_START)
	$TROOT/itunes_server.sh restart > /dev/console &
	;;
PURE-FTPD_STOP)
	$TROOT/pure_ftpd.sh stop > /dev/console &
	;;
PURE-FTPD)
	$TROOT/pure_ftpd.sh restart > /dev/console &
	;;
COMMIT)
	/etc/scripts/misc/profile.sh put >  /dev/console
	;;
WAN)
	$TROOT/wan.sh restart > /dev/console &
	;;
LAN)
	$TROOT/lan.sh delay_restart > /dev/console &
	$TROOT/itunes_server.sh delay_restart > /dev/console &
	;;
CLR_DEVSTATUS)
	/etc/scripts/misc/nclr-devstatus.sh 20 &
	;;
LAN_CHANGE)
	$TROOT/onlanchange.sh
	;;
HTTPD)
	$TROOT/webs.sh restart > /dev/console
	;;
HTTPD_PASSWD)
	$TROOT/webs.sh password > /dev/console
	$TROOT/neaps.sh restart
	logger -p 192.0 "Password changed"
	;;
REMOTE)
	$TROOT/rg.sh misc		> /dev/console
	xmldbc -A $TROOT/httpd/killallses.php
	$TROOT/webs.sh reload	> /dev/console
	;;
DHCPD)
	$TROOT/dhcpd.sh > /dev/console
	;;
DNSR)
	$TROOT/dnrd.sh restart > /dev/console &
	;;
TIME)
	if [ $SYNCWITH != "2" ]; then
	xmldbc -i -s /runtime/timeset 1
	fi
	$TROOT/timezone.sh
	$TROOT/ntp.sh start > /dev/console
	;;
WLAN)
	$TROOT/igmpproxy.sh stop		> /dev/console
	$TROOT/enable_gzone.sh stop 	> /dev/console
	$TROOT/wlan.sh restart 			> /dev/console
	$TROOT/enable_gzone.sh start 	> /dev/console 
	$TROOT/igmpproxy.sh start 		> /dev/console
	$TROOT/upnpd.sh restart 		> /dev/console &
	;;
WLAN_SCH)
	$TROOT/wifi/wlan_sch.sh restart > /dev/console
	$TROOT/igmpproxy.sh restart 	> /dev/console
	;;
RESET_WLAN)
	xmldbc -s /wireless/wps/configured	""
	xmldbc -s /wireless/ssid			"dlink"
	xmldbc -s /wireless/authtype		"0"
	xmldbc -s /wireless/encrypttype		"0"
	;;
SYSLOG)
	$TROOT/logs.sh > /dev/console &
	;;
FRESET)
	/etc/scripts/misc/freset.sh > /dev/console &
	;;
REBOOT)
	echo "sleep 3; /etc/templates/wan.sh stop > /dev/console" > /tmp/temp.bin
	sh /tmp/temp.bin &
	/etc/scripts/misc/nreboot.sh 3	> /dev/console &
	;;
RG)
	$TROOT/rg.sh flushall	> /dev/console &
	;;
RG_FIREWALL)
	$TROOT/rg.sh firewall	> /dev/console &
	;;
RG_IP_FILTER)
	$TROOT/rg.sh ipfilter	> /dev/console &
	;;
RG_MAC_FILTER)
	$TROOT/rg.sh macfilter	> /dev/console &
	;;
RG_BLOCKING)
	$TROOT/rg.sh blocking	> /dev/console &
	;;
RG_VSVR)
	$TROOT/rg.sh vrtsrv	> /dev/console &
	;;
RG_DMZ)
	$TROOT/rg.sh dmz	> /dev/console &
	;;
RG_MISC)
	/etc/scripts/misc/setwantype.sh	> /dev/console 
	$TROOT/rg.sh misc			> /dev/console
	$TROOT/rg.sh passthrough	> /dev/console
	$TROOT/igmpproxy.sh restart	> /dev/console
	$TROOT/upnpd.sh restart		> /dev/console &
	;;
RG_APP)
	$TROOT/rg.sh portt	> /dev/console &
	;;
DDNS)
	rm -rf /var/run/dyndns.html > /dev/console
	$TROOT/dyndns.sh	> /dev/console &
	;;
DDNS_TEST)
	$TROOT/dyndns_test.sh	> /dev/console &
	;;
SYSTEM)
	/etc/scripts/system.sh restart &
	;;
DO_WPS)
	$TROOT/wps.sh pin > /dev/console &
	;;
DO_WPS_PBC)
	$TROOT/wps.sh pbc > /dev/console &
	;;
ROUTE)
	$TROOT/route.sh restart > /dev/console &
	;;
CLEAR_LANG_PACK)
	umount /www/locale/alt
	echo "FFFFFFFFFFFFFFFF" > `cat /etc/config/langpack`
	;;
GZONE)
	$TROOT/gzone.sh restart			> /dev/console
	$TROOT/rg.sh misc		  		> /dev/console 
	$TROOT/rg.sh macfilter  		> /dev/console &
	;;
GZONE_ENABLE)
	$TROOT/enable_gzone.sh restart	> /dev/console
	$TROOT/igmpproxy.sh restart		> /dev/console
	;;
GZONE_LAYOUT)
#	$TROOT/wan.sh stop				> /dev/console
	$TROOT/gzone.sh stop			> /dev/console
	$TROOT/igmpproxy.sh stop		> /dev/console
	$TROOT/enable_gzone.sh stop 	> /dev/console
	$TROOT/wifi/wlan_sch.sh stop 	> /dev/console
	$TROOT/wlan.sh stop 			> /dev/console
	/etc/scripts/layout.sh restart	> /dev/console
	$TROOT/wlan.sh start 			> /dev/console
	$TROOT/wifi/wlan_sch.sh start 	> /dev/console
	$TROOT/enable_gzone.sh start 	> /dev/console 
	$TROOT/igmpproxy.sh start		> /dev/console
	$TROOT/gzone.sh start			> /dev/console
#	$TROOT/wan.sh start				> /dev/console
	;;
QOS)
	$TROOT/rg.sh qos > /dev/console 
	$TROOT/qos.sh restart > /dev/console &
	$TROOT/hw_nat.sh restart > /dev/console &
	;;
RG_ARP_ATTACK)
	$TROOT/rg.sh arp_attack	> /dev/console &
	;;
FRAMEIT_RESTART)
	$TROOT/fcrss_server.sh restart	> /dev/console &
	;;
*)
	echo "Usage: submit {COMMIT|WAN|LAN|WLAN|HTTPD|HTTPD_PASSWD|REMOTE|"
	echo "               DHCPD|DNSR|TIME|SYSLOG|FRESET|DDNS|DDNS_TEST|SYSTEM|DO_WPS|"
	echo "               RG|RG_FIREWALL|RG_IP_FILTER|RG_MAC_FILTER|RG_VSVR|RG_DMZ|RG_MISC|"
	echo "               RG_URL_FILTER|RG_DOMAIN_FILTER|RG_APP|ROUTE|CLEAR_LANG_PACK|"
	echo "               GZONE|GZONE_ENABLE|GZONE_LAYOUT|QOS|RG_ARP_ATTACK|FRAMEIT_RESTART|WOL|"
	echo "               HD_RESTART_SLEEPTIME|LCD_SET_TIMEOUT}"
	;;
esac
exit 0
