#
# Makefile:
#
# Copyright (C) 2003-2008 silex technology, Inc.
#
-include ../../path.mk
-include ../../arch.mk
-include ../customer.mk

#MODULEPATH = $(TARGET)/lib/modules/$(shell uname -r)
#INSTALLDIR = $(MODULEPATH)/kernel/drivers/usb/sxuptp
#KERNELSRC  = $(MODULEPATH)/build
CONFIGFILE = $(KERNELDIR)/.config

all:

clean: 

install:
#	mkdir -p $(INSTALLDIR)
	cp *.ko $(TARGET)/lib/modules/.
