/*
 * Automatically generated header file, don't edit!
 */
#define ELBOX_HAVE_DOT_CONFIG 1
#define ELBOX_FIRMWARE_VERSION "1.00"
#define ELBOX_FIRMWARE_REVISION "N/A"

/* Device Configuration */
#define ELBOX_FIRMWARE_SIGNATURE "N/A"
#undef  ELBOX_BOARD_DEFAULT
#undef  ELBOX_BOARD_WRGG14
#undef  ELBOX_BOARD_WRGG14C
#undef  ELBOX_BOARD_WRGG15C
#undef  ELBOX_BOARD_WRGG16
#undef  ELBOX_BOARD_WRGG19
#undef  ELBOX_BOARD_WRGG19_C
#undef  ELBOX_BOARD_WRGG19_C_ART
#undef  ELBOX_BOARD_WRGG19_C_HSPOT
#undef  ELBOX_BOARD_WRGG22
#undef  ELBOX_BOARD_WRGG23
#undef  ELBOX_BOARD_WRGG24
#undef  ELBOX_BOARD_WRGG27
#undef  ELBOX_BOARD_WRGG27HP
#undef  ELBOX_BOARD_WRGG27_3G
#undef  ELBOX_BOARD_WMXRG01E
#undef  ELBOX_BOARD_WMXRG02E
#undef  ELBOX_BOARD_WMXCO02E
#undef  ELBOX_BOARD_WRGN06
#undef  ELBOX_BOARD_WRGN06C
#undef  ELBOX_BOARD_WRGN09
#undef  ELBOX_BOARD_WRGN10
#undef  ELBOX_BOARD_WRGN13
#undef  ELBOX_BOARD_WRGN15
#undef  ELBOX_BOARD_WRGN15C
#undef  ELBOX_BOARD_WRGN16
#undef  ELBOX_BOARD_WRGN16A
#undef  ELBOX_BOARD_WRGN18
#undef  ELBOX_BOARD_WRGN18N
#undef  ELBOX_BOARD_SWRGN18
#undef  ELBOX_BOARD_WRGN19
#undef  ELBOX_BOARD_WRGN20
#undef  ELBOX_BOARD_RT3052
#undef  ELBOX_BOARD_WRGN22
#undef  ELBOX_BOARD_WRGN23
#undef  ELBOX_BOARD_WRGN28
#undef  ELBOX_BOARD_WRGND02
#undef  ELBOX_BOARD_WRGND03
#undef  ELBOX_BOARD_WRGND04
#undef  ELBOX_BOARD_WAPG14
#undef  ELBOX_BOARD_WAPG18
#undef  ELBOX_BOARD_WAPN03
#undef  ELBOX_BOARD_WAPN06
#undef  ELBOX_BOARD_WAPND01
#undef  ELBOX_BOARD_WAPND02
#undef  ELBOX_BOARD_WAPND03
#undef  ELBOX_BOARD_WAPND04
#undef  ELBOX_BOARD_WAPND06
#undef  ELBOX_BOARD_WAPN07
#define ELBOX_BOARD_WRGNS01 1
#undef  ELBOX_BOARD_WRGN27
#define ELBOX_BOARD_NAME "wrgns01"
#define ELBOX_INSTALL_LIBGCC_A_SO 1
#define ELBOX_BSP_STORM3516 1
#define ELBOX_BSP_NAME "storm3516"
#define ELBOX_LINUX_MAJOR 2
#define ELBOX_LINUX_MINOR 6
#define ELBOX_LINUX_BUILD 15
#define ELBOX_TEMPLATE_GW_WIFI 1
#undef  ELBOX_TEMPLATE_GW_WIFI_2WAN
#undef  ELBOX_TEMPLATE_AP_WIFI
#undef  ELBOX_TEMPLATE_AP_GAMING
#undef  ELBOX_TEMPLATE_AP_WIFI_WAN
#undef  ELBOX_TEMPLATE_TENDER
#undef  ELBOX_TEMPLATE_EMPTY
#undef  ELBOX_TEMPLATE_ARIES
#define ELBOX_TEMPLATE_NAME "gw.wifi"
#define ELBOX_BRAND_NAME "dlwbr"
#define ELBOX_MODEL_NAME "dir685"
#define ELBOX_TEMPLATE_GW_WIFI_GZONE 1
#undef  ELBOX_BRAND_GENERIC
#undef  ELBOX_BRAND_SEATTLE
#define ELBOX_BRAND_DLWBR 1
#undef  ELBOX_BRAND_AIRLINK
#undef  ELBOX_BRAND_CONCEPTRONIC
#undef  ELBOX_MODEL_DIR300
#undef  ELBOX_MODEL_DIR300B
#undef  ELBOX_MODEL_DIR300SZT
#undef  ELBOX_MODEL_DIR300ENTEL
#undef  ELBOX_MODEL_DIR300TELGUA
#undef  ELBOX_MODEL_DIR320
#undef  ELBOX_MODEL_DIR605
#undef  ELBOX_MODEL_DIR605B
#undef  ELBOX_MODEL_DIR615
#undef  ELBOX_MODEL_DIR320HP
#undef  ELBOX_MODEL_DIR465
#undef  ELBOX_MODEL_DIR815
#define ELBOX_MODEL_DIR685 1
#undef  ELBOX_MODEL_DIR605D1
#undef  ELBOX_MODEL_DIR600B

/* Brand/Model Selection */

/* Features configuration */
#undef  LOGNUM
#undef  ELBOX_USE_IPV6

/* Language Configuration */

/* Language options */
#define ELBOX_CREATE_LANGUAGE_PACK 1

/* Languages */
#define ELBOX_LANGUAGE_JA 1
#define ELBOX_LANGUAGE_DE 1
#define ELBOX_LANGUAGE_ZH_TW 1
#define ELBOX_LANGUAGE_ZH_CN 1
#define ELBOX_LANGUAGE_FR 1
#define ELBOX_LANGUAGE_ES 1
#define ELBOX_LANGUAGE_IT 1
#undef  ELBOX_LANGUAGE_NL
#undef  ELBOX_LANGUAGE_PT
#undef  ELBOX_LANGUAGE_FI
#undef  ELBOX_LANGUAGE_SV
#undef  ELBOX_LANGUAGE_NO
#undef  ELBOX_LANGUAGE_DA
#define ELBOX_LANGUAGE_KO 1
#undef  ELBOX_LANGUAGE_PL
#undef  ELBOX_LANGUAGE_RU
#undef  ELBOX_LANGUAGE_HE
#undef  ELBOX_LANGUAGE_HU
#undef  ELBOX_LANGUAGE_EL
#undef  ELBOX_LANGUAGE_TR
#undef  ELBOX_LANGUAGE_CS
#undef  ELBOX_LANGUAGE_TH
#undef  ELBOX_LANGUAGE_AR
#undef  ELBOX_LANGUAGE_IS

/* Default Language */

/* Programs Configuration */

/* GPL Programs */
#undef  ELBOX_ARP_SPOOF
#define ELBOX_PROGS_GPL_BPALOGIN 1
#define ELBOX_BUSYBOX 1
#undef  ELBOX_BUSYBOX_DYNAMIC_LINKING
#define ELBOX_PROGS_GPL_BUSYBOX_1_00 1
#define ELBOX_PROGS_GPL_BUSYBOX_1_00_ADVANCED_CONFIG 1
#undef  ELBOX_PROGS_GPL_TFTP_FTP_GET_PUT_FW_CONFIG
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_11_1
#undef  ELBOX_PROGS_GPL_CHILLISPOT
#undef  ELBOX_PROGS_GPL_DIBBLER
#define ELBOX_USE_DNS 1
#define ELBOX_PROGS_GPL_DNRD_2_10 1
#undef  ELBOX_PROGS_GPL_DNSMASQ
#undef  ELBOX_HOSTAPD
#define ELBOX_HTTPD 1
#define ELBOX_PROGS_GPL_MATHOPD 1
#undef  ELBOX_PROGS_GPL_MATHOPD_STANDARD
#undef  ELBOX_PROGS_GPL_MATHOPD_16

/* Upload externel file */
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_FILE
#define ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_BT_FILE 1
#undef  ELBOX_PROGS_GPL_IGMPPROXY
#undef  ELBOX_PROGS_GPL_IPPERSONALITY
#define ELBOX_PROGS_GPL_IPROUTE2_2_6_8 1
#define ELBOX_PROGS_GPL_TC_FOR_AP 1
#undef  ELBOX_PROGS_GPL_TC_U32_IP_PORT_RANGE
#define ELBOX_IPTABLES 1
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_6A
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_7A
#undef  ELBOX_PROGS_GPL_IPTABLES_1_2_9
#define ELBOX_PROGS_GPL_IPTABLES_1_3_5 1
#define ELBOX_IPTABLES_L7_EXT 1
#define ELBOX_PROGS_GPL_ITUNES_SERVER 1
#define ELBOX_KLOGD 1
#define ELBOX_PROGS_GPL_KLOGD 1
#undef  ELBOX_PROGS_GPL_KLOGD_AP
#undef  ELBOX_PROGS_GPL_LPRNG_3_8_27
#define ELBOX_PROGS_GPL_NSBBOX 1

/* NotSoBusyBOX configuration */
#undef  CONFIG_NSBBOX_BASE64
#define CONFIG_NSBBOX_BRCTL 1
#define CONFIG_NSBBOX_BRCTL_BWCTRL 1
#undef  CONFIG_NSBBOX_BRCTL_IOAPNL
#undef  CONFIG_NSBBOX_BRCTL_PORTFORWARD
#undef  CONFIG_NSBBOX_BRCTL_PORTDENYLIST
#undef  CONFIG_NSBBOX_BRCTL_IGMP
#undef  CONFIG_NSBBOX_BRCTL_AP_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_APC_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_DHCP_SERVER_ENABLE
#undef  CONFIG_NSBBOX_BRCTL_E_PARTITION
#undef  CONFIG_NSBBOX_BRCTL_ETHLINK
#undef  CONFIG_NSBBOX_BRCTL_LIMITED_ADMIN
#undef  CONFIG_NSBBOX_BRCTL_PING_CONTROL
#undef  CONFIG_NSBBOX_BRCTL_MULTI_VLAN
#undef  CONFIG_NSBBOX_BRCTL_MAT_STATUS
#undef  CONFIG_NSBBOX_BRCTL_MAC_CLONE
#define CONFIG_NSBBOX_NTPCLIENT 1
#undef  CONFIG_NSBBOX_SMTPCLIENT
#define CONFIG_NSBBOX_VCONFIG 1
#define ELBOX_PPPD 1
#define ELBOX_PROGS_GPL_PPPD_ALPHA 1

/* Accelerate pptp */
#undef  ELBOX_PROGS_GPL_PPPD_ACCEL_PPTP
#define ELBOX_PROGS_GPL_PURE_FTPD 1
#undef  ELBOX_PROGS_GPL_QUOTA
#undef  ELBOX_PROGS_GPL_RADVD
#define ELBOX_SAMBA 1
#undef  ELBOX_PROGS_GPL_SAMBA_3_0_7
#define ELBOX_PROGS_GPL_SAMBA_3_0_25a 1
#undef  ELBOX_PROGS_GPL_NET_SNMP
#undef  ELBOX_PROGS_GPL_STUNNEL
#undef  ELBOX_PROGS_GPL_STUPID_FTPD
#define ELBOX_USE_SYSLOG 1
#define ELBOX_PROGS_GPL_SYSLOGD 1
#undef  ELBOX_PROGS_GPL_SYSLOGD_V2
#undef  ELBOX_PROGS_GPL_SYSLOGD_REMOTELOG
#undef  ELBOX_PROGS_GPL_SYSLOGD_SMTP
#undef  ELBOX_PROGS_GPL_SYSLOGD_AP
#define ELBOX_PROGS_GPL_TELNETD 1
#undef  ELBOX_PROGS_GPL_TELNETD_CLIENT_CONNECTION_TIMEOUT
#undef  ELBOX_PROGS_GPL_TELNETD_GET_DATABASE
#define ELBOX_PROGS_GPL_TINYLOGIN 1
#undef  ELBOX_PROGS_GPL_TZCOMPILER
#define ELBOX_PROGS_GPL_UDEV 1
#define ELBOX_UDHCP 1

/* Use Unicasting and broadcasting request */
#undef  ELBOX_PROGS_GPL_UDHCP_REQUEST_BROADCAST
#undef  ELBOX_PROGS_GPL_UDHCP_0_9_8
#define ELBOX_PROGS_GPL_UDHCPCD 1
#undef  ELBOX_PROGS_GPL_UDHCP_RFC3442
#undef  ELBOX_PROGS_GPL_UDHCP_RFC2132
#undef  ELBOX_PROGS_GPL_UDHCP_HOLD_LAN_IP
#undef  ELBOX_PROGS_GPL_UPNPIGD
#define ELBOX_PROGS_GPL_USB_MODESWITCH 1
#undef  ELBOX_PROGS_GPL_WOL
#define ELBOX_PROGS_GPL_WIRELESS_TOOLS 1

/* IWLIST configuration */
#undef  CONFIG_IWLIST_APSCANN

/* IWPRIV configuration */
#undef  CONFIG_IWPRIV_APSCAN
#undef  ELBOX_PROGS_GPL_XSUPPLICANT
#undef  ELBOX_PROGS_GPL_ZEBRA
#undef  ELBOX_RADIUSCLIENT

/* ------------------------ Libraries ------------------------ --- */
#define ELBOX_PROGS_GPL_LIB_GSASL 1
#define ELBOX_PROGS_GPL_LIB_GSASL_0_2_6 1
#define ELBOX_OPENSSL 1
#undef  ELBOX_PROGS_GPL_OPENSSL_USE_STATIC_LINK
#undef  ELBOX_PROGS_GPL_OPENSSL_098A
#undef  ELBOX_PROGS_GPL_OPENSSL_098E
#undef  ELBOX_PROGS_GPL_OPENSSL_098E_GCC_4_2
#define ELBOX_PROGS_GPL_OPENSSL_098G 1
#undef  ELBOX_PROGS_GPL_LIBTORRENT
#undef  ELBOX_ZLIB
#undef  ELBOX_PROGS_GPL_EMAILCLIENT

/* Private Programs (developed by AlphaNetworks) */
#define ELBOX_XMLDB 1
#define ELBOX_PROGS_PRIV_XMLDB 1
#undef  ELBOX_PROGS_PRIV_XMLDB3
#define ELBOX_CREATE_RGDB_LINK_TO_XMLDBC 1
#define ELBOX_PROGS_PRIV_RGBIN 1

/* RGBIN configuration */

/* GPL tools - DO NOT use the GPL code here, use PROG.GPL/NSBBOX instead !! */
#undef  CONFIG_RGBIN_BASE64
#undef  CONFIG_RGBIN_BRCTL
#undef  CONFIG_RGBIN_NTPCLIENT
#undef  CONFIG_RGBIN_SMTPCLIENT
#undef  CONFIG_RGBIN_VCONFIG
#undef  CONFIG_RGBIN_BRCTL_WEB_REDIRECT

/* Private tools - ONLY use the private code here !! */
#undef  CONFIG_RGBIN_SEAMA
#undef  CONFIG_RGBIN_HTTPC
#undef  CONFIG_RGBIN_GENUUID
#define CONFIG_RGBIN_PFILE 1
#define CONFIG_RGBIN_SCUT 1
#define CONFIG_RGBIN_TLOGS 1
#define CONFIG_RGBIN_ASESSION 1
#undef  CONFIG_RGBIN_MPCONVERT
#define CONFIG_RGBIN_DAYCONVERT 1
#define CONFIG_RGBIN_CHNET 1
#undef  CONFIG_RGBIN_ROUTETABLE
#undef  CONFIG_RGBIN_PARSEINFO
#define CONFIG_RGBIN_LOGIN 1
#undef  CONFIG_RGBIN_ARPPING
#define CONFIG_RGBIN_GETHOSTIP 1
#undef  CONFIG_RGBIN_COREDE
#define CONFIG_RGBIN_USOCKC 1
#undef  CONFIG_RGBIN_SUSOCKC
#undef  CONFIG_RGBIN_RSTRCMP
#undef  CONFIG_RGBIN_GETSYS

/* DevData - Permanent Data */
#undef  CONFIG_RGBIN_DEVDATA

/* DevConf - User Configuration */
#undef  CONFIG_RGBIN_DEVCONF

/* outdated utilities */
#define ELBOX_RGBIN_RGCFG 1
#undef  CONFIG_RGBIN_RGCFG
#define CONFIG_RGBIN_RGCFG2 1
#undef  CONFIG_RGBIN_testflash
#define CONFIG_RGCFG_BLOCK_OFFSET 0
#define CONFIG_RGCFG_BLOCK_SIZE 65536
#undef  CONFIG_RGBIN_RGDB
#define CONFIG_RGBIN_TCPREQUEST 1
#define ELBOX_ALPHA_XGI 1
#define ELBOX_PROGS_PRIV_ALPHA_XGI 1
#undef  ELBOX_IPSEC_PT
#define ELBOX_IFRESETCNT 1
#undef  ELBOX_PROGS_PRIV_IFRESETCNT
#define ELBOX_PROGS_PRIV_IFRESETCNT_26 1
#undef  ELBOX_STUN_NAT
#undef  ELBOX_TURBONAT
#undef  ELBOX_PROGS_PRIV_APX
#define ELBOX_LOG_MESSAGE 1
#define ELBOX_PROGS_PRIV_LOG_ENGLISH 1
#undef  ELBOX_MADWIFI
#undef  ELBOX_PROGS_PRIV_ART_AP83
#undef  ELBOX_PROGS_PRIV_MADWIFI_AP83
#undef  ELBOX_PROGS_PRIV_MADWIFI_CAVIUM
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM
#undef  ELBOX_RALINK_WIFI
#define ELBOX_PROGS_PRIV_RALINK_INIC 1
#undef  ELBOX_PROGS_PRIV_RALINK_INIC_RT2880_1170
#undef  ELBOX_PROGS_PRIV_RALINK_INIC_RT2880_1180
#undef  ELBOX_PROGS_PRIV_RALINK_INIC_RT2880_1181
#define ELBOX_PROGS_PRIV_RALINK_INIC_RT2880_1183 1
#undef  ELBOX_RT2860V2
#undef  ELBOX_PROGS_PRIV_RT2860V2_STA
#undef  ELBOX_RT2561
#undef  ELBOX_BROADCOM_WIFI
#define ELBOX_PROGS_PRIV_UPNPKITS 1

/* UPnP kits configuration */
#define CONFIG_UPNPKITS_HNAP 1
#define CONFIG_UPNPKITS_UPNPKITS 1
#define CONFIG_UPNPKITS_UPNPDEV 1
#define CONFIG_UPNPKITS_WFADEV 1
#define CONFIG_UPNPKITS_WFANOTIFY 1
#define CONFIG_UPNPKITS_WFANOTIFY_SERVICE_ROOT_NODE "/runtime/upnpdev/root:2/service:1"
#undef  CONFIG_UPNPKITS_UPNPCP
#undef  CONFIG_UPNPKITS_COREGA_ROUTER
#define CONFIG_UPNPKITS_GENUUID 1
#define ELBOX_PROGS_PRIV_NEAPS 1

/* Neap Server Class Configuration */
#define CONFIG_NEAPS_INTERNET 1
#define CONFIG_NEAPS_WIRELESS 1
#define CONFIG_NEAPS_RESIDENTIAL_GATEWAY 1
#undef  ELBOX_PROGS_PRIV_AP_NEAP
#undef  ELBOX_PROGS_PRIV_IGMP
#define ELBOX_PROGS_PRIV_IGMPPROXY 1

/* igmpproxy configuration */
#define ELBOX_PROGS_PRIV_IGMPPROXY_IGMPV3 1
#define ELBOX_PROGS_PRIV_SCHEDULED 1
#define ELBOX_PROGS_PRIV_COMMON_SCRIPTS 1

/* 3g support */
#undef  ELBOX_PROGS_PRIV_COMMON_SCRIPTS_3G_PLUG_AND_PLAY
#define ELBOX_PROGS_PRIV_COMMON_SCRIPTS_UDEV_USB_3G_HOTPLUG 1
#define ELBOX_PROGS_PRIV_ALPHA3GTOOL 1
#define ELBOX_PROGS_PRIV_DHCPXMLPATCH 1
#undef  ELBOX_PROGS_PRIV_UPDATELEASES
#undef  ELBOX_PROGS_PRIV_MTDTEST
#define ELBOX_PROGS_PRIV_PORTT 1
#undef  ELBOX_PROGS_PRIV_NETSTAR
#undef  ELBOX_PROGS_PRIV_RESOLVED
#undef  ELBOX_PROGS_PRIV_PROXYD
#define ELBOX_DDNS 1

/* Select DDNS updater implementation */
#define ELBOX_PROGS_PRIV_DYNDNS 1
#undef  ELBOX_PROGS_PRIV_PEANUT
#undef  ELBOX_PROGS_PRIV_BDTOOL
#undef  ELBOX_PROGS_PRIV_BDCFG
#define ELBOX_PROGS_PRIV_LLD2D 1
#define ELBOX_PROGS_PRIV_CMCGI 1
#undef  ELBOX_PROGS_PRIV_ART
#define ELBOX_PROGS_PRIV_WIDGET 1
#undef  ELBOX_PROGS_PRIV_STARSPEED
#undef  ELBOX_PROGS_PRIV_TR069_CLIENT
#undef  ELBOX_PROGS_PRIV_TRAFFICCTRL
#undef  ELBOX_PROGS_PRIV_ALPHA_HOTPLUG
#define ELBOX_PROGS_PRIV_WCN_UFD 1
#undef  ELBOX_PROGS_PRIV_MADWIFI_DUALBAND
#define ELBOX_PROGS_PRIV_ALPHA_NLS_DRV 1
#define ELBOX_PROGS_PRIV_WPSTOOLS 1

/* WPS tools configuration */
#undef  CONFIG_WPSTOOLS_BIG_ENDIAN
#undef  CONFIG_WPSTOOLS_PROFILE_HELPER
#undef  CONFIG_WPSTOOLS_USE_SHARED_OPENSSL
#undef  CONFIG_WPSTOOLS_STA_SUPPORT
#undef  CONFIG_WPSTOOLS_ALPHA_BACKUP_RADIUS_SERVER
#undef  CONFIG_WPSTOOLS_ALPHA_NAP_SERVER_SUPPORT
#define CONFIG_WPSTOOLS_ALPHA_UNSUPPORT_PRAGMA_PACK 1
#undef  CONFIG_WPSTOOLS_RADIUS_SERVER_ON_BOARD
#undef  CONFIG_WPSTOOLS_DISABLE_HOSTAPD
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT_0_5
#undef  ELBOX_PROGS_PRIV_CAPWAP
#undef  ELBOX_PROGS_PRIV_CLI
#define ELBOX_FIRMWARE_HEADER_VERSION_CONTROL 1
#define ELBOX_FIRMWARE_HEADER_VERSION 3
#define ELBOX_FIRMWARE_CONTROL_FLAG1 0
#define ELBOX_FIRMWARE_CONTROL_FLAG2 0
#define ELBOX_FIRMWARE_RESERVED_FLAG1 0
#define ELBOX_FIRMWARE_RESERVED_FLAG2 0
#undef  ELBOX_FIRMWARE_FLASH_SP_MX
#define ELBOX_WLXMLPATCHV2 1
#define ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK 1
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_MADWIFI

/* Ralink model selection */
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT2800
#undef  ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT61
#define ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT2880 1
#define ELBOX_PROGS_PRIV_WLXMLPATCHV2_RALINK_RT2880_v1183 1
#undef  ELBOX_UPDATEWIFISTATS
#undef  ELBOX_PROGS_PRIV_NETBIOS
#undef  ELBOX_PROGS_PRIV_ETHLINK
#define ELBOX_PROGS_PRIV_SENDMAIL 1
#undef  ELBOX_PROGS_PRIV_STATIC_DHCP
#undef  ELBOX_PROGS_PRIV_SERVD
#undef  ELBOX_PROGS_PRIV_CGIBIN_ARIES
#define ELBOX_PROGS_PRIV_UPNP_AV 1
#define ELBOX_PROGS_PRIV_VERIFICATION_CODE 1
#undef  ELBOX_PROGS_PRIV_CLONED
#undef  ELBOX_PROGS_PRIV_LOGD
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY_CLIENT
#undef  ELBOX_PROGS_PRIV_DDNSD
#undef  ELBOX_PROGS_PRIV_DHCPPLUS
#undef  ELBOX_PROGS_PRIV_TRAP_MONITOR
#undef  ELBOX_PROGS_PRIV_AUTOREKEY

/* Common library configuration */
#define ELBOX_COMLIB_MEM_HELPER_DISABLE 1
